// import { Dimensions } from 'react-native'
// export const Dimensions={
//     width:Dimensions.get('window').width,
//     height:Dimensions.get('window').height,
// }
export const  ImagePath = {
    deleveryBoy : require('./images/hhh.png'),
    Food:require('./images/Fooding.png'),
    gift:require('./images/gift.png'),
    Food2:require('./images/food.png'),
    h1:require('./images/bargar.png'),
    pizza:require('./images/pizza.png'),
    french:require('./images/french.png'),
    Cheese:require('./images/che.png'),
    Address:require('./images/gpr.png'),
    Star:require('./images/Black.png'),
    Fastfood:require('./images/moms.png'),
    Dinair:require('./images/aalupodhi.png'),
    ppp:require('./images/panner.png'),
    pizz:require('./images/pizzatali.png'),
    Eat:require('./images/Eating.png'),
    Rectangle:require('./images/Rectangle.png'),
    pppnir:require('./images/pppnir.png'),
    Nood:require('./images/Noodles.png'),
    Past:require('./images/Pasta.png'),
    Mooms:require('./images/M.png'),
    AddressDelivery:require('./images/Delivery.png'),
    Atm:require('./images/card.png'),
    Bank:require('./images/House.png'),
    JJJ:require('./images/jjjj.png'),
}
export const IconPath={
    home:require('./Icons/home.png'),
    Food:require('./Icons/gg.png'),
    Marketing:require('./Icons/Instamart.png'),
    Vector:require('./Icons/Genie.png'),
    Arror:require('./Icons/kkk.png'),
    ArrorUp:require('./Icons/ArrorUp.png'),
    Heart:require('./Icons/Heart.png'),
    ArrorRight:require('./Icons/ArrorRight.png'),
    Discount:require('./Icons/Discount.png'),
    Setting:require('./Icons/Setting.png'),
    Back:require('./Icons/Back.png'),
    Login:require('./Icons/Login.png'),
    GPS:require('./Icons/GPS.png'),
    arrordawon:require('./Icons/arrordawon.png'),
    Sarch:require('./Icons/Sarch.png'),
    Sound:require('./Icons/sound.png'),
    str1:require('./Icons/str.png'),
    Switch:require('./Icons/Gol.png'),
    Switch2:require('./Icons/Gol2.png'),
    Login:require('./Icons/lll.png'),
    Arr:require('./Icons/Arrord.png')
}